NPCchats:
  1: #農夫工會會長
    1:
      msg: "早呀! 我是農夫工會會長!"
      next: 
        1:
          msg: "農夫是甚麼?"
          to: 2
        2:
          msg: "如何成為農夫?"
          to: 3
  2: #匠人工會會長
    1:
      msg: "我是匠人工會會長, 沒事別來吵我好嗎。"
      next: 
        1:
          msg: "匠人是甚麼?"
          to: "2"
        2:
          msg: "如何成為匠人?"
          to: "3"

      